# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wenplus-docker-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://wenpluspreprod.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_84017fde21504264bc087d0f9fa51bf6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b02766923f44decbe005a4467bfe2f0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wenpluspreprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84017fde21504264bc087d0f9fa51bf6 }}/wenplus-docker-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wenplus-docker-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae2efe68fafb4cb8b0e6656a8fd61348 }}
        images: 'wenpluspreprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84017fde21504264bc087d0f9fa51bf6 }}/wenplus-docker-api:${{ github.sha }}'